# Generated by Django 4.2.5 on 2023-10-04 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thing',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='thing',
            name='name',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='thing',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
