# Generated by Django 4.2.5 on 2023-10-04 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0003_alter_thing_description_alter_thing_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thing',
            name='description',
            field=models.TextField(blank=True, default='', max_length=119),
        ),
        migrations.AlterField(
            model_name='thing',
            name='name',
            field=models.TextField(default='', max_length=29, unique=True),
        ),
    ]
