# Generated by Django 4.2.5 on 2023-10-04 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0005_alter_thing_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thing',
            name='description',
            field=models.TextField(blank=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='thing',
            name='name',
            field=models.TextField(default='', max_length=30, unique=True),
        ),
    ]
