# Generated by Django 4.2.5 on 2023-10-04 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0006_alter_thing_description_alter_thing_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thing',
            name='description',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='thing',
            name='name',
            field=models.CharField(default='', max_length=30, unique=True),
        ),
    ]
